app:
  name: trading-report
  version: 1.0.0

spring:
  profiles:
    active: standalone
  mongodb:
    uri: mongodb+srv://dbUserReport:SaxHrEMtjJ4yyYw2@clustermongo.6boi9dc.mongodb.net
    database: trading_report_des


